trigger:
  batch: true
  branches:
    include:
      - master

pool: Default

workspace:
  clean: all

variables:
  - group: Nuget
  - name: outputFolder
    value: $(Build.SourcesDirectory)/_output
  - name: testResultsFolder
    value: $(outputFolder)/TestResults

steps:
  - task: NuGetToolInstaller@1
    displayName: Install NuGet

  - pwsh: |
      dotnet restore
    displayName: NuGet restore

  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: $(Build.SourcesDirectory)/Kros.Utils.MsAccess.sln
      msbuildArgs: /verbosity:normal /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:OutDir="$(outputFolder)"
      platform: Any CPU
      configuration: Release

  - pwsh: |
      & "$(outputFolder)/Kros.Utils.MsAccess.UnitTests.exe" -trx "$(testResultsFolder)/Kros.Utils.MsAccess.UnitTests.xml"
    displayName: Test

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**/*.xml'
      searchFolder: $(testResultsFolder)

  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    - pwsh: |
        nuget pack "$(Build.SourcesDirectory)/src/Kros.Utils.MsAccess.csproj" -Build -OutputDirectory "$(Build.artifactStagingDirectory)"
      displayName: NuGet pack

    - pwsh: |
        $nupkgFiles = Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)" -Filter "*.nupkg"
        Write-Host "Found $($nupkgFiles.Count) .nupkg file(s) to push"
        foreach ($nupkgFile in $nupkgFiles) {
          Write-Host "Pushing $($nupkgFile.FullName)"
          & nuget push "$($nupkgFile.FullName)" -Source https://nuget.org -ApiKey $(nugetOrgApiKey) -SkipDuplicate
          Write-Host
        }
      displayName: NuGet push
