trigger:
  batch: true
  branches:
    include:
      - master

pool: Default

workspace:
  clean: all

variables:
  - group: Nuget
  - name: outputFolder
    value: $(Build.SourcesDirectory)/_output
  - name: testResultsFolder
    value: $(outputFolder)/TestResults

steps:
  - pwsh: |
      dotnet restore "$(Build.SourcesDirectory)/Kros.Utils.MsAccess.sln"
    displayName: NuGet restore

  - pwsh: |
      dotnet build "$(Build.SourcesDirectory)/src/Kros.Utils.MsAccess.csproj" --configuration Release
    displayName: Build library

  - pwsh: |
      dotnet build "$(Build.SourcesDirectory)/tests/Kros.Utils.MsAccess.UnitTests.csproj" --configuration Release --output "$(outputFolder)/tests"
    displayName: Build tests

  - pwsh: |
      & "$(outputFolder)/tests/Kros.Utils.MsAccess.UnitTests.exe" -trx "$(testResultsFolder)/Kros.Utils.MsAccess.UnitTests.xml"
    displayName: Run tests

  - task: PublishTestResults@2
    displayName: Publish test results
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**/*.xml'
      searchFolder: $(testResultsFolder)

  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    - pwsh: |
        dotnet pack "$(Build.SourcesDirectory)/src/Kros.Utils.MsAccess.csproj" --configuration Release --output "$(Build.artifactStagingDirectory)"
      displayName: NuGet pack

    - pwsh: |
        $nupkgFiles = Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)" -Filter "*.nupkg"
        Write-Host "Found $($nupkgFiles.Count) .nupkg file(s) to push"
        foreach ($nupkgFile in $nupkgFiles) {
          Write-Host "Pushing $($nupkgFile.FullName)"
          & dotnet nuget push "$($nupkgFile.FullName)" --source https://api.nuget.org/v3/index.json --api-key $(nugetOrgApiKey) --skip-duplicate
          Write-Host
        }
      displayName: NuGet push
