trigger:
  batch: true
  branches:
    include:
    - master

pool: Default

resources:
  repositories:
    - repository: templates
      type: git
      name: DevShared/Templates

variables:
  - group: Nuget
  - name: 'buildPlatform'
    value: 'any cpu'
  - name: buildConfiguration
    value: 'Release'
  - name: solution
    value: 'Kros.Utils.MsAccess.sln'
  - name: projectName
    value: 'Kros.Utils.MsAccess'

steps:
  - template: steps/nuget-download.yml@templates

  - template: steps/nuget-restore.yml@templates
    parameters:
      useNugetConfig: 'false'

  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/verbosity:normal /p:DeployOnBuild=true /p:SkipInvalidConfigurations=true'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: Tests
    inputs:
      command: test
      projects: '**/*test*.csproj'
      nobuild: true
