CREATE TABLE [IdStore] (
	[TableName] nvarchar(100) NOT NULL,
	[LastId] int NOT NULL,

	CONSTRAINT [PK_IdStore] PRIMARY KEY CLUSTERED ([TableName] ASC)	WITH (
		PAD_INDEX = OFF,
		STATISTICS_NORECOMPUTE = OFF,
		IGNORE_DUP_KEY = OFF,
		ALLOW_ROW_LOCKS = ON,
		ALLOW_PAGE_LOCKS = ON
	)
)
