//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kros.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kros.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination table &quot;{0}&quot; does not have column &quot;{1}&quot;..
        /// </summary>
        internal static string BulkInsertColumnDoesNotExistInDestination {
            get {
                return ResourceManager.GetString("BulkInsertColumnDoesNotExistInDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid destination column mapping at index {0}..
        /// </summary>
        internal static string BulkInsertInvalidDestinationColumnMapping {
            get {
                return ResourceManager.GetString("BulkInsertInvalidDestinationColumnMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to change index name if it already belongs to some table. The index &quot;{0}&quot; belong to table &quot;{1}&quot;..
        /// </summary>
        internal static string CannotChangeIndexNameWhenIndexBelongsToTable {
            get {
                return ResourceManager.GetString("CannotChangeIndexNameWhenIndexBelongsToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument value must be {0}. Current value is {1}..
        /// </summary>
        internal static string Check_Equal {
            get {
                return ResourceManager.GetString("Check_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument value must be greater or equal than {0}. Current value is {1}..
        /// </summary>
        internal static string Check_GreaterOrEqualThan {
            get {
                return ResourceManager.GetString("Check_GreaterOrEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument value must be greater than {0}. Current value is {1}..
        /// </summary>
        internal static string Check_GreaterThan {
            get {
                return ResourceManager.GetString("Check_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is invalid. It must be one of the allowed values: {1}.
        /// </summary>
        internal static string Check_IsInListDefaultMessage {
            get {
                return ResourceManager.GetString("Check_IsInListDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is invalid. It cannot be one of disallowed values: {1}.
        /// </summary>
        internal static string Check_IsNotInListDefaultMessage {
            get {
                return ResourceManager.GetString("Check_IsNotInListDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be of type {0}..
        /// </summary>
        internal static string Check_IsNotOfType {
            get {
                return ResourceManager.GetString("Check_IsNotOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is not of required type {0}. Argument&apos;s type is {1}..
        /// </summary>
        internal static string Check_IsOfType {
            get {
                return ResourceManager.GetString("Check_IsOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument value must be less or equal than {0}. Current value is {1}..
        /// </summary>
        internal static string Check_LessOrEqualThan {
            get {
                return ResourceManager.GetString("Check_LessOrEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument value must be less than {0}. Current value is {1}..
        /// </summary>
        internal static string Check_LessThan {
            get {
                return ResourceManager.GetString("Check_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty GUID is not allowed..
        /// </summary>
        internal static string Check_NotEmptyGuid {
            get {
                return ResourceManager.GetString("Check_NotEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument value {0} is not allowed..
        /// </summary>
        internal static string Check_NotEqual {
            get {
                return ResourceManager.GetString("Check_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null..
        /// </summary>
        internal static string Check_NotNull {
            get {
                return ResourceManager.GetString("Check_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null, neither empty string..
        /// </summary>
        internal static string Check_StringNotNullOrEmpty {
            get {
                return ResourceManager.GetString("Check_StringNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null, neither empty string, nor string containing only whitespace characters..
        /// </summary>
        internal static string Check_StringNotNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Check_StringNotNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &quot;{0}&quot; cannot be added to index &quot;{1}&quot; because it already belongs to index &quot;{2}&quot;..
        /// </summary>
        internal static string ColumnBelongsToAnotherIndex {
            get {
                return ResourceManager.GetString("ColumnBelongsToAnotherIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &quot;{0}&quot; cannot be added to table &quot;{1}&quot; because it already belongs to table &quot;{2}&quot;..
        /// </summary>
        internal static string ColumnBelongsToAnotherTable {
            get {
                return ResourceManager.GetString("ColumnBelongsToAnotherTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination table &quot;{0}&quot; does not have column &quot;{1}&quot;..
        /// </summary>
        internal static string ColumnMissingInBulkInsertDestinationTable {
            get {
                return ResourceManager.GetString("ColumnMissingInBulkInsertDestinationTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination column name nor its ordinal is set..
        /// </summary>
        internal static string DestinationColumnMappingNotSet {
            get {
                return ResourceManager.GetString("DestinationColumnMappingNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; for ADO client &quot;{1}&quot; is not registered..
        /// </summary>
        internal static string FactoryNotRegisteredForClient {
            get {
                return ResourceManager.GetString("FactoryNotRegisteredForClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; for connection type &quot;{1}&quot; is not registered..
        /// </summary>
        internal static string FactoryNotRegisteredForConnection {
            get {
                return ResourceManager.GetString("FactoryNotRegisteredForConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign key &quot;{0}&quot; cannot be added to table &quot;{1}&quot; because it already belongs to table &quot;{2}&quot;..
        /// </summary>
        internal static string ForeignKeyBelongsToAnotherTable {
            get {
                return ResourceManager.GetString("ForeignKeyBelongsToAnotherTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index &quot;{0}&quot; cannot be added to table &quot;{1}&quot; because it already belongs to table &quot;{2}&quot;..
        /// </summary>
        internal static string IndexBelongsToAnotherTable {
            get {
                return ResourceManager.GetString("IndexBelongsToAnotherTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column ordinal can not be negative..
        /// </summary>
        internal static string InvalidBulkInsertColumnMappingOrdinal {
            get {
                return ResourceManager.GetString("InvalidBulkInsertColumnMappingOrdinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination table &quot;{0}&quot; does not contain column at index {1}..
        /// </summary>
        internal static string InvalidIndexInDestinationColumnMapping {
            get {
                return ResourceManager.GetString("InvalidIndexInDestinationColumnMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination table &quot;{0}&quot; does not contain column &quot;{1}&quot;..
        /// </summary>
        internal static string InvalidNameInDestinationColumnMapping {
            get {
                return ResourceManager.GetString("InvalidNameInDestinationColumnMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;{0}&quot; does not have property &quot;{1}&quot; which is in column names list..
        /// </summary>
        internal static string MissingPropertyInType {
            get {
                return ResourceManager.GetString("MissingPropertyInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the path parts contains invalid characters. Erroneous part is at index {0}: &quot;{1}&quot;.
        /// </summary>
        internal static string PathContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("PathContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For loading the database schema, the database name (Initial Catalog) must be specified in the connection..
        /// </summary>
        internal static string SqlServerNoInitialCatalog {
            get {
                return ResourceManager.GetString("SqlServerNoInitialCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported connection type. The connection must be of type SqlConnection..
        /// </summary>
        internal static string SqlServerUnsupportedConnectionType {
            get {
                return ResourceManager.GetString("SqlServerUnsupportedConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &quot;{0}&quot; cannot be added to database &quot;{1}&quot; because it already belongs to database &quot;{2}&quot;..
        /// </summary>
        internal static string TableBelongsToAnotherDatabase {
            get {
                return ResourceManager.GetString("TableBelongsToAnotherDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported database connection type: {0}.
        /// </summary>
        internal static string UnsupportedConnectionType {
            get {
                return ResourceManager.GetString("UnsupportedConnectionType", resourceCulture);
            }
        }
    }
}
